server:
  port: 8081
  servlet:
    session:
      timeout: 30m
    context-path: /
  tomcat:
    max-http-post-size: 5MB
    max-swallow-size: 5MB
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
#  main:
#    banner-mode: "on"
#  profiles:
#    active: redis
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: "spring:session:xuexifang"
#    timeout: 30m
#  cache:
#    type: redis
#    redis:
#      time-to-live: 120s
#      key-prefix: "xuexifang-cache-"
#      cache-null-values: false
  #    cache-names: products, userInfo
#    type: caffeine
#    caffeine:
#      spec: initialCapacity=10,maximumSize=1000,expireAfterWrite=60s
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
#nutz:
#  json:
#    auto-unicode: true
#    mode: compact
#    quote-name: false
#    date-format: yyyy-MM-dd HH:mm:ss
#    actived: true
#    ignore-null: true
#    indent: 8
#    enabled: true
